CREATE DATABASE GreenLifeH
GO

USE GreenLifeH

CREATE TABLE CategoriaProduto
(
IdCategoriaProduto UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Fornecedor
(
IdFornecedor UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
NomeFantasia VARCHAR(100) UNIQUE NOT NULL,
CNPJ VARCHAR(14) UNIQUE NOT NULL
);


CREATE TABLE Produto
(
IdProduto UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome VARCHAR(100) UNIQUE NOT NULL,
Preco DECIMAL(10, 2) NOT NULL,
Imagem VARCHAR(100),
IdCategoriaProduto UNIQUEIDENTIFIER FOREIGN KEY REFERENCES CategoriaProduto(IdCategoriaProduto),
IdFornecedor UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Fornecedor(IdFornecedor)
);